version: '3.9'

services:
  teraflex-api:
    depends_on:
      - teraflex-db
    container_name: teraflex-api
    image: node:18-alpine
    working_dir: /app
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: sh -c "yarn install && yarn start:dev"
  teraflex-db:
    container_name: ${DATABASE_HOST}
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - teraflex-data:/var/lib/postgresql/data

volumes:
  teraflex-data:
