version: '3.9'

services:
  teraflex-api:
    depends_on:
      - teraflex-db
    container_name: teraflex-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./.env
  teraflex-db:
    container_name: ${DATABASE_HOST}
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - teraflex-data:/var/lib/postgresql/data

volumes:
  teraflex-data:
